### ISSUE TITLE
Support for custom prefix for cashaddress

### ISSUE THREAD

**Issue by damascene** [ebellocchia/py_crypto_hd_wallet#11]
Bitcoin cash has the special prefix `bitcoincash:` that was created to avoid sending funds to other networks by mistake. Few other protocols and networks use similar prefix like:

- Simple Ledger Protocol (BCH tokens): `simpleledger:` 
- Ergon proportional block rewards based stable coin: `ergon:`
- Ecash, BCH fork: `ecash:`

Those also comes with their test net variants. for the time being I'm using this conversion library. https://github.com/PiRK/ecashaddress

Hopefully you can add support to custom prefixes in your library so it would be easy to generate addresses for multiple different coins.

**Comment by ebellocchia** [comment]
Hi,
thanks for the information, I didn't know about these prefixes.
Yes sure, I can add some enums for those.
If what changes is only the prefix (i.e. same coin index), as a workaround (for now) you can generate addresses with a custom prefix by using bip_utils directly:

    from bip_utils import (
        Bip39WordsNum, Bip39MnemonicGenerator, Bip39SeedGenerator, Bip44Changes, Bip44Coins, Bip44PublicKey, Bip44,
        BchP2PKHAddr, CoinsConf
    )

    def AddrWithCustomPrefix(bip44_pub_key: Bip44PublicKey,
                             hrp: str) -> str:
        # For BIP49, BchP2SHAddr with p2sh_std_net_ver shall be used
        return BchP2PKHAddr.EncodeKey(bip44_pub_key.Bip32Key().KeyObject(),
                                      hrp=hrp,
                                      net_ver=CoinsConf.BitcoinCashMainNet.Params("p2pkh_std_net_ver"))

    # Generate random mnemonic
    mnemonic = Bip39MnemonicGenerator().FromWordsNumber(Bip39WordsNum.WORDS_NUM_24)
    print(f"Mnemonic: {mnemonic}")
    # Generate seed from mnemonic
    seed_bytes = Bip39SeedGenerator(mnemonic).Generate()

    # Construct from seed
    bip44_mst_ctx = Bip44.FromSeed(seed_bytes, Bip44Coins.BITCOIN_CASH)
    # Generate BIP44 change keys
    bip44_chg_ctx = bip44_mst_ctx.Purpose().Coin().Account(0).Change(Bip44Changes.CHAIN_EXT)

    # Generate some addresses with different prefixes
    for i in range(5):
        bip44_addr_ctx = bip44_chg_ctx.AddressIndex(i)
        print(f"{i}. Address: {bip44_addr_ctx.PublicKey().ToAddress()}")
        print(f"{i}. Address: {AddrWithCustomPrefix(bip44_addr_ctx.PublicKey(), 'simpleledger')}")
        print(f"{i}. Address: {AddrWithCustomPrefix(bip44_addr_ctx.PublicKey(), 'ecash')}")

**Comment by ebellocchia** [comment]
I added SLP and eCash coins (_HdWalletBip44Coins.BITCOIN_CASH_SLP_, _HdWalletBip44Coins.BITCOIN_CASH_SLP_TESTNET_, _HdWalletBip44Coins.ECASH_, _HdWalletBip44Coins.ECASH_TESTNET_ - Same for Bip49) and a small class for converting Bitcoin Cash addresses, in case other prefixes are needed:

    from bip_utils import BchAddrConverter

    # Convert address by change the HRP (the old net version is maintained)
    conv_addr = BchAddrConverter.Convert("bitcoincash:qp90dvzptg759efdcd93s4dkdw0vuhlkmqlch7letq", "ergon")
    # Convert address by change both HRP  and net version
    conv_addr = BchAddrConverter.Convert("bitcoincash:qp90dvzptg759efdcd93s4dkdw0vuhlkmqlch7letq", "customprefix", b"\x01")

This can be used for converting the addresses generated by _py_crypto_hd_wallet_

You just need to upgrade _bip_utils_ because the enums of _py_crypto_hd_wallet_ are just aliases.

**Comment by damascene** [comment]
Awesome, thank you Emanuele. Do you mind posting a BCH address for a little tip?
