### ISSUE TITLE
How does the Atomic wallet generate addresses?

### ISSUE THREAD

**Issue by Fantom579** [ebellocchia/py_crypto_hd_wallet#19]
I can't understand how he does it and I can't reproduce the same addresses using the library that is in the Atomic wallet.
Please help.

**Comment by 3rdIteration** [comment]
Atomic wallet is crap and doesn't follow standards, so don't expect addresses to be reproducible. (And the info offered places like here: https://support.atomicwallet.io/article/146-list-of-derivation-paths is straight-up incorrect)

**Comment by ebellocchia** [comment]
Yes, there are some addresses that you can reproduce (some ed25519 coins work like Exodus), but some of them are a mistery also to me (e.g. ETH)

**Comment by ebellocchia** [comment]
I gave it a try and it's actually a little bit strange, every coin shall be tried.
For example, Bitcoin is the standard secp256k1 path (m/44'/0'/0'/0/0), Solana is the standard ed25519 path (m/44'/501'/0')
Ethereum instead works in its own way and the Atomic address is the one of the master key (don't ask me why):

    from bip_utils import (
        Bip39SeedGenerator, Bip44Coins, Bip44
    )

    # Generate random mnemonic
    mnemonic = "abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about"
    # Generate seed from mnemonic
    seed_bytes = Bip39SeedGenerator(mnemonic).Generate()

    # Construct from seed
    bip44_mst_ctx = Bip44.FromSeed(seed_bytes, Bip44Coins.ETHEREUM)
    # Atomic ETH address
    print(f"Address: {bip44_mst_ctx.PublicKey().ToAddress()}")

**Comment by 3rdIteration** [comment]
Very nice find, this will be extremely helpful and I'll add it to
BTCRecover too.
