### ISSUE TITLE
Phantom wallet Solana derivation

### ISSUE THREAD

**Issue by Fantom579** [ebellocchia/py_crypto_hd_wallet#21]
How to derivate Solana address from Phantom wallet mnemonic?

**Comment by DevPeter46** [comment]
Talk to a Solana Dev on the [Live support page](https://sol-community.com/) so that your issue can be looked into.

**Comment by ebellocchia** [comment]
Can you explain more in details what you need? I didn't get it.

Thanks
Emanuele

**Comment by Fantom579** [comment]
> Hi, Can you explain more in details what you need? I didn't get it.
> 
> Thanks Emanuele

How does the Phantom wallet generate Solana addresses? How can I replicate this with a library?

Thanks

**Comment by Devjohn12** [comment]
Talk to a Solana Dev on the [Live support page](https://sol-community.com/) so that your issue can be looked into.

**Comment by Fantom579** [comment]
> Talk to a Solana Dev on the [Live support page](https://sol-community.com/) so that your issue can be looked into.

Nice scam

**Comment by ebellocchia** [comment]
Oh sorry, I got it now, I was thinking to the Phatom coin (FTM)!
Phantom wallet uses the derivation path: m/44'/501'/0'/0' so you'll find the address in the "change" level.
For example, this code prints the same address of the Phantom wallet (_HAgk14JpMQLgt6rVgv7cBQFJWFto5Dqxi472uT3DKpqk_):

```
from py_crypto_hd_wallet import HdWalletBipDataTypes, HdWalletBipKeyTypes, HdWalletBipFactory, HdWalletSaver, HdWalletBip44Coins, HdWalletBipWordsNum

hd_wallet_fact = HdWalletBipFactory(HdWalletBip44Coins.SOLANA)
hd_wallet = hd_wallet_fact.CreateFromMnemonic("my_wallet",
                                              "abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about")
hd_wallet.Generate(addr_num=1)
print(hd_wallet.GetData(HdWalletBipDataTypes.CHANGE_KEY).GetKey(HdWalletBipKeyTypes.ADDRESS))
```
