### ISSUE TITLE
Solana "Public child derivation is not supported"

### ISSUE THREAD

**Issue by SSez** [ebellocchia/py_crypto_hd_wallet#22]
bip_utils.bip.bip32.bip32_ex.Bip32KeyError: Public child derivation is not supported

![Code_oiOm5uT1lT](https://user-images.githubusercontent.com/26654418/160722330-dd8034f6-3368-4375-a20e-25e3d713f38f.png)
d

**Comment by ebellocchia** [comment]
Hi,
Solana doesn't support public derivation so you cannot create a watch-only wallet from a public key.

Regards,
Emanuele
