### ISSUE TITLE
Support Polygon Mumbai Testnet

### ISSUE THREAD

**Issue by jsmellz** [ebellocchia/py_crypto_hd_wallet#5]
Does the Polygon "Mumbai" testnet work with this HD Wallet implementation?

**Comment by ebellocchia** [comment]
Hi, if the address of the test network is the same of the main network yes, you can use Ethereum or Polygon to generate the keys

**Comment by jsmellz** [comment]
Thanks

**Comment by jsmellz** [comment]
@ebellocchia should I use the path m/44'/60 still?

**Comment by ebellocchia** [comment]
Yes it's always the same path. For Ethereum, usually the path of the first address is m/44'/60'/0'/0/0 (some wallets may use different paths like m/44'/60'/0'/0 or m/44'/60'/0').

**Comment by jsmellz** [comment]
Thanks
