### ISSUE TITLE
some network dosnot work

### ISSUE THREAD

**Issue by bitycle** [ebellocchia/py_crypto_hd_wallet#7]
package version 0.14.0 dos not work and this eror occur.

![Screenshot from 2021-07-24 10-48-10](https://user-images.githubusercontent.com/87688517/126859499-6016a747-33a9-4366-b13c-d283ce1dc679.png)

**Comment by ebellocchia** [comment]
Hi,
I think you are using the old bip_utils, you should install the version 2.0.0 from the repo to use it with 0.14.0

Thanks
