### ISSUE TITLE
Feature Request: Chia Support

### ISSUE THREAD

**Issue by dendisuhubdy** [ebellocchia/py_crypto_hd_wallet#8]
Any plans for chia support?

**Comment by ebellocchia** [comment]
Hi,
I should add it before to the bip_utils lib. If it uses an elliptic curve that is already supported, I don't see any problem adding it.

Thanks

**Comment by dendisuhubdy** [comment]
@ebellocchia I've read some of the Chia python code, if i would want to contribute, how would you suggest me to add another coin like Chia HD pub-priv wallet generation?

**Comment by ebellocchia** [comment]
Hi,
i took a quick look to Chia code but it doesn't follow BIP44 (it follows: https://eips.ethereum.org/EIPS/eip-2334) and it uses a BLS curve that it's not currently supported by the library, so it won't be easy to add it (it requires a new curve and this new EIP-2334 implementation). However, if you want to try following the structure of other elliptic curves and coins, you'll be welcome of course.

**Comment by ebellocchia** [comment]
Not planned for now
